### ISSUE TITLE
Todos listed twice

### ISSUE THREAD

**Issue by bojidar-bg** [need12648430/godot-todo#1]
(Godot 2.1.3-alpha/HEAD (custom build))

![image](https://cloud.githubusercontent.com/assets/5276727/23139189/d45a3828-f7b3-11e6-9a9a-e51abe3930c3.png)

As you can see, `game.gd:22` and `letter_grid.gd:34,61` are listed more than once. Fixme comments seem to work fine though.

**Comment by need12648430** [comment]
Are game.gd and letter_grid.gd linked to nodes in the editor?

It's possible it's yanking it from both a .tscn that references the script and the .gd file itself. I'll fix it later this evening.

**Comment by need12648430** [comment]
Think I fixed the problem with ac974bf. I'll update the asset library - though it'll be some time before it's authorized.

**Comment by bojidar-bg** [comment]
Cool, you might just close the issue then, and reopen if problem persists, I guess.

(BTW, good job, this plugin looks great :smiley: )
